/**
 * [INPUT]: 依赖 content/ 的真实首个案例文件，依赖 node:zlib 生成纯色 PNG
 * [OUTPUT]: 默认导出 buildFixtures()，生成 tests/fixtures/.generated/content（taxonomy、合成条目、fixture 化的首个案例与图片）；直接执行时即生成
 * [POS]: tests/fixtures 的测试数据生成器：Vitest globalSetup 与 E2E webServer 各调用一次；所有记录带 fixture:true，生产内容根会拒绝它们
 * [PROTOCOL]: Update this header when making changes, then check README.md.
 */
import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { crc32, deflateSync } from "node:zlib";

const OUT = path.join(process.cwd(), "tests", "fixtures", ".generated", "content");
const REAL_SLUG = "grokbot-capsule-icon";
const EXAMPLE_RIGHTS = { basis: "Synthetic fixture image", evidence: "Generated by tests/fixtures/build.ts" };

function png(width: number, height: number, [r, g, b]: [number, number, number]): Buffer {
  const chunk = (type: string, data: Buffer) => {
    const body = Buffer.concat([Buffer.from(type, "ascii"), data]);
    const out = Buffer.alloc(8 + data.length + 4);
    out.writeUInt32BE(data.length, 0);
    body.copy(out, 4);
    out.writeUInt32BE(crc32(body), 8 + data.length);
    return out;
  };
  const header = Buffer.alloc(13);
  header.writeUInt32BE(width, 0);
  header.writeUInt32BE(height, 4);
  header.set([8, 2, 0, 0, 0], 8);
  const row = Buffer.alloc(1 + width * 3);
  for (let x = 0; x < width; x++) row.set([r, g, b], 1 + x * 3);
  const raw = Buffer.concat(Array.from({ length: height }, () => row));
  return Buffer.concat([Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]), chunk("IHDR", header), chunk("IDAT", deflateSync(raw)), chunk("IEND", Buffer.alloc(0))]);
}

const json = (file: string, value: unknown) => writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`);

function writeImage(slug: string, id: string, width: number, height: number, color: [number, number, number]) {
  const dir = path.join(OUT, "prompts", slug, "images");
  mkdirSync(dir, { recursive: true });
  writeFileSync(path.join(dir, `${id}.png`), png(width, height, color));
  return { src: `images/${id}.png`, width, height };
}

export default function buildFixtures() {
  rmSync(OUT, { recursive: true, force: true });
  mkdirSync(path.join(OUT, "prompts"), { recursive: true });

  const taxonomy = JSON.parse(readFileSync("content/taxonomy.json", "utf8"));
  taxonomy.categories.push(
    { id: "illustration", labels: { en: "Illustration", "zh-CN": "插画" }, descriptions: { en: "Fixture illustration prompts.", "zh-CN": "测试用插画条目。" } },
    { id: "logos", labels: { en: "Logos", "zh-CN": "标志" }, descriptions: { en: "A category with no entries.", "zh-CN": "没有条目的分类。" } },
  );
  taxonomy.tags.push({ id: "watercolor", labels: { en: "Watercolor", "zh-CN": "水彩" } }, { id: "fixture-only", labels: { en: "Fixture", "zh-CN": "测试" } });
  json(path.join(OUT, "taxonomy.json"), taxonomy);

  // The real first entry, published with synthetic images so editor/detail flows can be exercised end to end.
  const realDir = path.join(OUT, "prompts", REAL_SLUG);
  cpSync(path.join("content", "prompts", REAL_SLUG), realDir, { recursive: true });
  const meta = JSON.parse(readFileSync(path.join(realDir, "meta.json"), "utf8"));
  json(path.join(realDir, "meta.json"), {
    ...meta,
    fixture: true,
    status: "published",
    publishedAt: "2026-09-20",
    featuredRank: 1,
    redirectFrom: ["grokbot-icon-legacy"],
  });
  const defaults = { faceColor: "cream", blush: "oval", background: "charcoal", composition: "lower-left", tilt: "15", coloring: "pastel", outline: "none" };
  json(path.join(realDir, "examples.json"), [
    {
      id: "fixture-dark",
      ...writeImage(REAL_SLUG, "fixture-dark", 1000, 1000, [40, 40, 44]),
      alt: { en: "Fixture: solid dark square standing in for a bot icon", "zh-CN": "测试图：代替机器人头像的深色方块" },
      sourceUrl: "https://grokbot-icon-studio.serio-ai.chatgpt.site/en",
      provenance: "source-reported",
      rights: EXAMPLE_RIGHTS,
      recipe: null,
    },
    {
      id: "fixture-verified",
      ...writeImage(REAL_SLUG, "fixture-verified", 1000, 1000, [70, 60, 90]),
      alt: { en: "Fixture: solid plum square with a recorded recipe", "zh-CN": "测试图：带生成记录的梅紫色方块" },
      sourceUrl: "https://github.com/thinkingjimmy/Image-Prompt-Book",
      provenance: "project-verified",
      rights: EXAMPLE_RIGHTS,
      recipe: { templateVersion: "2.0.0", outputLocale: "en", selections: defaults, model: "fixture-model", generatedAt: "2026-09-21" },
    },
  ]);

  // Synthetic entries: enough for two pages, mixed aspect ratios, one long title and one hostile string.
  const SIZES: [number, number][] = [[800, 1000], [1000, 1000], [1000, 700], [700, 1200]];
  for (let index = 1; index <= 29; index++) {
    const slug = `fixture-sample-${String(index).padStart(2, "0")}`;
    const dir = path.join(OUT, "prompts", slug);
    mkdirSync(dir, { recursive: true });
    const [width, height] = SIZES[index % SIZES.length]!;
    const watercolor = index % 3 === 0;
    const hostile = index === 7;
    const longTitle = index === 5;
    const day = String(1 + (index % 28)).padStart(2, "0");
    const title = hostile
      ? `<script>window.__pwned=1</script> Hostile sample`
      : longTitle
        ? "An intentionally very long fixture title that keeps going to check wrapping and clamping in narrow gallery columns"
        : `Fixture sample ${index}`;

    json(path.join(dir, "meta.json"), {
      schemaVersion: 1,
      id: slug,
      slug,
      templateVersion: "1.0.0",
      status: "published",
      createdAt: "2026-08-01",
      updatedAt: `2026-08-${day}`,
      publishedAt: `2026-08-${day}`,
      featuredRank: index === 2 ? 2 : null,
      fixture: true,
      category: "illustration",
      tags: watercolor ? ["watercolor", "fixture-only"] : ["fixture-only"],
      originalLocale: "en",
      contentLocales: ["en", "zh-CN"],
      outputLocales: ["en", "zh-CN"],
      originalPath: "original.en.txt",
      templatePaths: { en: "template.en.txt", "zh-CN": "template.zh-CN.txt" },
      parametersPath: "parameters.json",
      examplesPath: "examples.json",
      requiresReferenceImage: false,
      sourceRecommendedTools: [],
      verifiedModels: [],
      sources: [{ id: "fixture", type: "github", role: "original", title: "Fixture source", url: "https://github.com/thinkingjimmy/Image-Prompt-Book", checkedAt: "2026-09-23" }],
      rights: { promptLicense: "MIT", licenseUrl: "https://opensource.org/license/mit", sourceLicenseUrl: null, commercialUse: "allowed" },
    });
    for (const locale of ["en", "zh-CN"] as const) {
      const zh = locale === "zh-CN";
      json(path.join(dir, `${locale}.json`), {
        title: zh && !hostile && !longTitle ? `测试样例 ${index}` : title,
        summary: hostile ? `<img src=x onerror="window.__pwned=2"> summary` : zh ? `用于测试瀑布流的合成条目 ${index}。` : `Synthetic gallery entry ${index}${watercolor ? " in watercolor" : ""}.`,
        seoTitle: `Fixture ${index}`,
        seoDescription: `Fixture ${index} description`,
        inputRequirement: zh ? "无需参考图。" : "No reference image needed.",
        howToUse: [zh ? "复制 Prompt。" : "Copy the prompt."],
        exampleNotice: zh ? "测试图片。" : "Fixture image.",
        verificationNotice: zh ? "未验证。" : "Not verified.",
        adaptationNotice: zh ? "测试内容。" : "Fixture content.",
        licenseNotice: "MIT",
        parameterLabels: { style: zh ? "风格" : "Style" },
        ...(index === 9 ? { keywords: ["zebra"] } : {}),
      });
    }
    writeFileSync(path.join(dir, "original.en.txt"), `Draw a fixture picture number ${index}.\n`);
    writeFileSync(path.join(dir, "template.en.txt"), `[Goal]\n\nDraw a {{style}} fixture picture number ${index}.\n`);
    writeFileSync(path.join(dir, "template.zh-CN.txt"), `[目标]\n\n画一张{{style}}的测试图 ${index}。\n`);
    json(path.join(dir, "parameters.json"), {
      schemaVersion: 1,
      parameters: [
        {
          id: "style",
          type: "select",
          renderAs: "inline",
          default: "flat",
          options: [
            { id: "flat", labels: { en: "Flat", "zh-CN": "平面" }, replacements: { en: "flat", "zh-CN": "平面风格" } },
            { id: "sketch", labels: { en: "Sketch", "zh-CN": "素描" }, replacements: { en: "sketched", "zh-CN": "素描风格" } },
          ],
        },
      ],
    });
    const shade = 120 + ((index * 37) % 120);
    json(path.join(dir, "examples.json"), [
      {
        id: "cover",
        ...writeImage(slug, "cover", width, height, [shade, 200 - (index % 5) * 20, 230 - shade / 3]),
        alt: { en: `Fixture color block ${index}`, "zh-CN": `测试色块 ${index}` },
        sourceUrl: "https://github.com/thinkingjimmy/Image-Prompt-Book",
        provenance: "source-reported",
        rights: EXAMPLE_RIGHTS,
        recipe: null,
      },
    ]);
    writeFileSync(
      path.join(dir, "ATTRIBUTION.md"),
      `# Attribution — ${slug}\n\n## en\n\n\`\`\`text\nFixture attribution ${index}\n\`\`\`\n\n## zh-CN\n\n\`\`\`text\n测试署名 ${index}\n\`\`\`\n`,
    );
  }

  // A draft that must never become reachable.
  const draftDir = path.join(OUT, "prompts", "fixture-draft");
  cpSync(path.join(OUT, "prompts", "fixture-sample-01"), draftDir, { recursive: true });
  const draftMeta = JSON.parse(readFileSync(path.join(draftDir, "meta.json"), "utf8"));
  json(path.join(draftDir, "meta.json"), { ...draftMeta, id: "fixture-draft", slug: "fixture-draft", status: "draft", publishedAt: null, examplesPath: "examples.json" });
  json(path.join(draftDir, "examples.json"), []);

  console.log(`Fixture content written to ${path.relative(process.cwd(), OUT)}`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) buildFixtures();
